// <auto-generated />
using System;
using G_NET_12_EF05;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace G_NET_12_EF05.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("G_NET_12_EF05.Models.Account", b =>
                {
                    b.Property<int>("AccountNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountNumber"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BranchCode")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OpeingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AccountNumber");

                    b.HasIndex("BranchCode");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("G_NET_12_EF05.Models.Branch", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.HasIndex("ManagerId")
                        .IsUnique();

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Code = 101,
                            Address = "Cairo",
                            ManagerId = 1,
                            Name = "Main Branch",
                            PhoneNumber = "19000"
                        },
                        new
                        {
                            Code = 102,
                            Address = "Giza",
                            ManagerId = 2,
                            Name = "Giza Branch",
                            PhoneNumber = "16222"
                        },
                        new
                        {
                            Code = 103,
                            Address = "Alex",
                            ManagerId = 3,
                            Name = "Alex Branch",
                            PhoneNumber = "18000"
                        });
                });

            modelBuilder.Entity("G_NET_12_EF05.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("G_NET_12_EF05.Models.CustomerAccount", b =>
                {
                    b.Property<int>("AccountAccountNumber")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("AccountStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OwnershipStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnershipType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountAccountNumber", "CustomerId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerAccounts");
                });

            modelBuilder.Entity("G_NET_12_EF05.Models.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ahmed@bank.com",
                            FullName = "Ahmed Ali",
                            HireDate = new DateTime(2026, 5, 6, 22, 7, 32, 806, DateTimeKind.Local).AddTicks(6461),
                            PhoneNumber = "010112345"
                        },
                        new
                        {
                            Id = 2,
                            Email = "yasmine@bank.com",
                            FullName = "Yasmine Ahmed",
                            HireDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0122333444"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Omer@bank.com",
                            FullName = "OmerTaha",
                            HireDate = new DateTime(2026, 5, 6, 22, 7, 32, 806, DateTimeKind.Local).AddTicks(6590),
                            PhoneNumber = "0156789820"
                        });
                });

            modelBuilder.Entity("G_NET_12_EF05.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionNumber"));

                    b.Property<int>("AccountAccountNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionNumber");

                    b.HasIndex("AccountAccountNumber");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("G_NET_12_EF05.Models.Account", b =>
                {
                    b.HasOne("G_NET_12_EF05.Models.Branch", "BranchACC")
                        .WithMany("AccountsBR")
                        .HasForeignKey("BranchCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BranchACC");
                });

            modelBuilder.Entity("G_NET_12_EF05.Models.Branch", b =>
                {
                    b.HasOne("G_NET_12_EF05.Models.Manager", "ManagersBR")
                        .WithOne("BranchsMA")
                        .HasForeignKey("G_NET_12_EF05.Models.Branch", "ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagersBR");
                });

            modelBuilder.Entity("G_NET_12_EF05.Models.CustomerAccount", b =>
                {
                    b.HasOne("G_NET_12_EF05.Models.Account", "AccountCA")
                        .WithMany("CustomerAccountA")
                        .HasForeignKey("AccountAccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("G_NET_12_EF05.Models.Customer", "CustomerCA")
                        .WithMany("CustomerAccountC")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountCA");

                    b.Navigation("CustomerCA");
                });

            modelBuilder.Entity("G_NET_12_EF05.Models.Transaction", b =>
                {
                    b.HasOne("G_NET_12_EF05.Models.Account", "AccountTr")
                        .WithMany("TransactionsAC")
                        .HasForeignKey("AccountAccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountTr");
                });

            modelBuilder.Entity("G_NET_12_EF05.Models.Account", b =>
                {
                    b.Navigation("CustomerAccountA");

                    b.Navigation("TransactionsAC");
                });

            modelBuilder.Entity("G_NET_12_EF05.Models.Branch", b =>
                {
                    b.Navigation("AccountsBR");
                });

            modelBuilder.Entity("G_NET_12_EF05.Models.Customer", b =>
                {
                    b.Navigation("CustomerAccountC");
                });

            modelBuilder.Entity("G_NET_12_EF05.Models.Manager", b =>
                {
                    b.Navigation("BranchsMA")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
